### ISSUE TITLE
Compute Express Link (CXL) support

### ISSUE THREAD

**Issue by ohault** [enjoy-digital/litepcie#109]
Do you plan to add support for [CXL](https://www.computeexpresslink.org/)?

**Comment by enjoy-digital** [comment]
This is an interested topic, but a huge project by itself. Such developments are generally done with the help of partners interested and this hasn't been planned yet but we are of course open to discuss to possibilities to would help this this happen :)

**Comment by enjoy-digital** [comment]
Hi @ohault,

sorry, but this does not seems to be a realistic feature. That's probably is a > 6 months/developer effort that would need to be funded/discussed together if that something you would like to see happening. I have a preference to only keep realistic features/issues open. If you are interested by this features, please get in touch directly and we'll discuss what can be done.

Regards,

Florent
