### ISSUE TITLE
Implementing a versatile PCIe switch using LitePCIe

### ISSUE THREAD

**Issue by ohault** [enjoy-digital/litepcie#117]
Using the current version of LitePCIe, how difficult it would be to implement a PCIe switch using LitePCIe ?

Would it make sense to package it as new core in LitePCIe architecture?

It can be later extended to support:
- Non Transparent Bridging (NTB) - https://github.com/enjoy-digital/litepcie/issues/110
- Virtual Partitioning
- Multicasting
- Failover 

As a starting point, LitePCIeWishboneBridge would already be a PCIe bridge.

Towards a PCIe switch, Frame Buffer, Route Table, Port Arbitration and Scheduler would be required.
Support of multiple upstream ports should be better designed first to avoid later refactoring.

**Comment by enjoy-digital** [comment]
Hi @ohault,

sorry, but this does not seems to be a realistic feature. That's probably is a > 6 months/developer effort that would need to be funded/discussed together if that something you would like to see happening. I have a preference to only keep realistic features/issues open. If you are interested by this features, please get in touch directly and we'll discuss what can be done.

Regards,

Florent
