### ISSUE TITLE
Building userspace software without a crossover UART

### ISSUE THREAD

**Issue by daveshah1** [enjoy-digital/litepcie#40]
I found while working on the Alveo U250 that the user software build fails when a normal, non-crossover UART is used; as `CSR_UART_BASE` is defined but `CSR_UART_XOVER_RXEMPTY_ADDR` isn't:

<pre>gcc -c -O2 -Wall -g -I../kernel -MMD -o litepcie_util.o litepcie_util.c
<b>litepcie_util.c:</b> In function ‘<b>uart_test</b>’:
<b>litepcie_util.c:458:33:</b> <font color="#CC0000"><b>error: </b></font>‘<b>CSR_UART_XOVER_RXEMPTY_ADDR</b>’ undeclared (first use in this function); did you mean ‘<b>CSR_UART_RXEMPTY_ADDR</b>’?
  458 |         if ((litepcie_readl(fd, <font color="#CC0000"><b>CSR_UART_XOVER_RXEMPTY_ADDR</b></font>) &amp; 0x1) == 0) {
      |                                 <font color="#CC0000"><b>^~~~~~~~~~~~~~~~~~~~~~~~~~~</b></font>
      |                                 <font color="#4E9A06">CSR_UART_RXEMPTY_ADDR</font>
<b>litepcie_util.c:458:33:</b> <font color="#06989A"><b>note: </b></font>each undeclared identifier is reported only once for each function it appears in
<b>litepcie_util.c:459:45:</b> <font color="#CC0000"><b>error: </b></font>‘<b>CSR_UART_XOVER_RXTX_ADDR</b>’ undeclared (first use in this function); did you mean ‘<b>CSR_UART_RXTX_ADDR</b>’?
  459 |             printf(&quot;%c&quot;, litepcie_readl(fd, <font color="#CC0000"><b>CSR_UART_XOVER_RXTX_ADDR</b></font>) &amp; 0xff);
      |                                             <font color="#CC0000"><b>^~~~~~~~~~~~~~~~~~~~~~~~</b></font>
      |                                             <font color="#4E9A06">CSR_UART_RXTX_ADDR</font>
make: *** [Makefile:20: litepcie_util.o] Error 1</pre>

I think the `#ifdef` needs to be changed to something more specific.

**Comment by enjoy-digital** [comment]
Thanks for reporting, fixed with https://github.com/enjoy-digital/litepcie/commit/00927a2f702aed4c3e99d5aa8a5cc0e058c6840b.
