### ISSUE TITLE
Figure out if the cocotbext-pcie library can be used to test litepcie?

### ISSUE THREAD

**Issue by mithro** [enjoy-digital/litepcie#47]
Just recently found [PCI express simulation framework for Cocotb](https://github.com/alexforencich/cocotbext-pcie). I wonder if it makes any sense to try and use this to help verify LitePCIe?

**Comment by enjoy-digital** [comment]
This could indeed be useful to test the core against another model but we should probably first improve the unit-tests of the core (as we did recently with LiteDRAM for example).
