### ISSUE TITLE
LitePCIeDMALoopback  behavior

### ISSUE THREAD

**Issue by jimmymagemtek** [enjoy-digital/litepcie#52]
Hi Sir,
Could you describe the behavior of LitePCIeDMALoopback class in more details ?
It means that the data transferred by some RX buffer descriptor in DMA READER table will go directly to the destination of the corresponding TX buffer descriptor in DMA WRITER  table?

Thanks.
Jimmy

**Comment by enjoy-digital** [comment]
Hi @jimmymagemtek,

LitePCIeDMALoopback is just doing a loopback between the TX->RX loopback of the DMAs. This is used to validate the Host->DMAReader->DMAWriter->Host flow.

**Comment by enjoy-digital** [comment]
Closing since question has been answered.
