### ISSUE TITLE
DMA Loopback test fails on Acorn CLE-101

### ISSUE THREAD

**Issue by MattEttus** [enjoy-digital/litepcie#86]
Built using:
$  ./sqrl_acorn.py --variant cle-101 --with-pcie --uart-name crossover --build 

With Vivado 2021.2

$ ./litepcie_util dma_test
Unable to find DMA RX_DELAY (min errors: 2048/2048), exiting.

litepcie_util scratch register test and info both work.

**Comment by enjoy-digital** [comment]
@MattEttus: I've been able to reproduce on an Acorn CLE101 and no longer see it with https://github.com/enjoy-digital/litepcie/commit/1a0857323b51780d6d45f4e1e3865d42b1b98299 and https://github.com/enjoy-digital/litepcie/commit/d3af0fcfd805d834b19ed287ecb7b4c689f612be.
